### ISSUE TITLE
Claims request had header "Connection: close" when header is "Connection: keep-alive"

### ISSUE THREAD

**Issue by jameshfisher** [kennethreitz/httpbin#434] opened 2018-03-27 21:18 UTC
Steps to reproduce: 

```
$ cat <<EOF | unix2dos | nc httpbin.org 80
> POST /post HTTP/1.1
> Host: httpbin.org
> Content-Length: 0
> Connection: keep-alive
>
> POST /post HTTP/1.1
> Host: httpbin.org
> Content-Length: 0
> Connection: close
>
> EOF
HTTP/1.1 200 OK
Connection: keep-alive
Server: meinheld/0.6.1
Date: Tue, 27 Mar 2018 21:13:16 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Powered-By: Flask
X-Processed-Time: 0
Content-Length: 249
Via: 1.1 vegur

{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Connection": "close",
    "Content-Length": "0",
    "Host": "httpbin.org"
  },
  "json": null,
  "origin": "51.6.191.132",
  "url": "http://httpbin.org/post"
}
HTTP/1.1 200 OK
Connection: close
Server: meinheld/0.6.1
Date: Tue, 27 Mar 2018 21:13:15 GMT
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
X-Powered-By: Flask
X-Processed-Time: 0
Content-Length: 249
Via: 1.1 vegur

{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Connection": "close",
    "Content-Length": "0",
    "Host": "httpbin.org"
  },
  "json": null,
  "origin": "51.6.191.132",
  "url": "http://httpbin.org/post"
}
```

Notice that the first HTTP response sent back has this section:

```
"headers": {
    "Connection": "close",
    ...
```

This is not correct; it should say:

```
"headers": {
    "Connection": "keep-alive",
    ...
```

As an HTTP server, httpbin seems to obey the `Connection` header correctly. However, the JSON body does not return the headers that were sent.

**Comment by nateprewitt** [comment] 2018-03-27 21:21
Hi @jameshfisher, this is a duplicate of a number of other issues, the most recent being #432. Please be sure to check closed issues before opening new ones in the future. Thank you!

**Closed by nateprewitt** 2018-03-27 21:21 UTC
